version: '3.8'
services:
  pgadmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=
      - PGADMIN_DEFAULT_PASSWORD=
    ports:
      - 8877:80
    networks:
      - nginx.docker

networks:
  nginx.docker:
    name: nginx.docker
    external: true
