version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    networks:
      - nginx.docker

networks:
  nginx.docker:
    name: nginx.docker
    external: true

